{% set name = "MDRestraintsGenerator" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/MDRestraintsGenerator-{{ version }}.tar.gz
  sha256: 031e96539e9fae0048b501026f5d596e518693bf8f4ada3afc80e37c284e98d3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - mdanalysis >1.0.0
    - numpy
    - scipy
    - matplotlib-base

test:
  imports:
    - MDRestraintsGenerator
  # disable `pip check` because of the old scipy upper bound set
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/IAlibay/MDRestraintsGenerator/
  summary: Enabling the use of restraints in alchemical simulations
  license: LGPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
